"""initial schema

Revision ID: 570702d1f582
Revises: 
Create Date: 2026-07-03 03:05:01.819176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570702d1f582'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key')
    )
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('common_name', sa.String(length=120), nullable=False),
    sa.Column('cert_type', sa.Enum('TLS_SERVER', 'CODE_SIGN', 'OIDC_JWT', 'MUTUAL_TLS', 'ROOT_CA', 'ATTESTATION', name='certificatetype', native_enum=False), nullable=False),
    sa.Column('key_algorithm', sa.String(length=30), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_frameworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum('SOC2', 'ISO27001', 'GDPR', 'HIPAA', name='frameworkcode', native_enum=False), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('subtitle', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('auditor', sa.String(length=120), nullable=True),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('cert_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('config_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.Enum('CRITICAL', 'NECESSARY', 'OPTIONAL', name='configtier', native_enum=False), nullable=False),
    sa.Column('value_type', sa.Enum('STRING', 'INTEGER', 'BOOLEAN', 'DURATION', 'ENUM', 'JSON', name='configvaluetype', native_enum=False), nullable=False),
    sa.Column('active_value', sa.Text(), nullable=False),
    sa.Column('pending_value', sa.Text(), nullable=True),
    sa.Column('allowed_values', sa.String(length=500), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('requires_restart', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_parameters_key'), 'config_parameters', ['key'], unique=True)
    op.create_index(op.f('ix_config_parameters_section'), 'config_parameters', ['section'], unique=False)
    op.create_index(op.f('ix_config_parameters_tier'), 'config_parameters', ['tier'], unique=False)
    op.create_table('crypto_algorithms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('purpose_label', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ops_per_second', sa.Float(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('engine_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('availability_zone', sa.String(length=30), nullable=False),
    sa.Column('cluster_role', sa.Enum('PRIMARY', 'REPLICA', 'STANDBY', name='clusterrole', native_enum=False), nullable=False),
    sa.Column('build_hash', sa.String(length=40), nullable=False),
    sa.Column('build_branch', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_operational', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_uuid')
    )
    op.create_table('hsm_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('purpose', sa.Enum('PRIMARY', 'SIGNING', 'TENANT_DEK', 'STANDBY', name='slotpurpose', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('object_count', sa.Integer(), nullable=False),
    sa.Column('capacity_max_objects', sa.Integer(), nullable=False),
    sa.Column('ops_per_second', sa.Float(), nullable=False),
    sa.Column('token_flags', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_number')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.Enum('P1', 'P2', 'P3', name='incidentseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('UNASSIGNED', 'IN_PROGRESS', 'RESOLVED', name='incidentstatus', native_enum=False), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('sla_minutes', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('schema_validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint_path', sa.String(length=120), nullable=False),
    sa.Column('schema_ref', sa.String(length=120), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('tenant_slug', sa.String(length=80), nullable=True),
    sa.Column('reference_id', sa.String(length=60), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('org_id', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.Enum('ENTERPRISE', 'PREMIUM', 'STANDARD', name='tenanttier', native_enum=False), nullable=False),
    sa.Column('isolation_mode', sa.Enum('STRICT', 'STANDARD', 'SHARED', name='isolationmode', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PROVISIONING', 'SUSPENDED', 'DECOMMISSIONED', name='tenantstatus', native_enum=False), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('db_schema_name', sa.String(length=80), nullable=False),
    sa.Column('db_schema_valid', sa.Boolean(), nullable=False),
    sa.Column('network_cidr', sa.String(length=40), nullable=True),
    sa.Column('network_vpc', sa.String(length=30), nullable=True),
    sa.Column('network_shared', sa.Boolean(), nullable=False),
    sa.Column('dek_label', sa.String(length=60), nullable=True),
    sa.Column('encryption_valid', sa.Boolean(), nullable=False),
    sa.Column('events_per_second', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('anomaly_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='anomalyseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='anomalystatus', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('baseline_sigma', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_category'), 'anomaly_events', ['category'], unique=False)
    op.create_index(op.f('ix_anomaly_events_occurred_at'), 'anomaly_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_anomaly_events_severity'), 'anomaly_events', ['severity'], unique=False)
    op.create_index(op.f('ix_anomaly_events_status'), 'anomaly_events', ['status'], unique=False)
    op.create_index(op.f('ix_anomaly_events_tenant_id'), 'anomaly_events', ['tenant_id'], unique=False)
    op.create_table('api_endpoint_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_instance_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_path', sa.String(length=120), nullable=False),
    sa.Column('requests_per_second', sa.Float(), nullable=False),
    sa.Column('throttled_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('latency_p99_ms', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engine_instance_id'], ['engine_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_endpoint_stats_engine_instance_id'), 'api_endpoint_stats', ['engine_instance_id'], unique=False)
    op.create_index(op.f('ix_api_endpoint_stats_recorded_at'), 'api_endpoint_stats', ['recorded_at'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='auditseverity', native_enum=False), nullable=False),
    sa.Column('event_type', sa.Enum('STATE_CHANGE', 'AUTH_EVENT', 'CONFIG_CHANGE', 'POLICY_EVAL', 'TENANT_LIFECYCLE', 'KEY_OPERATION', 'ANOMALY_DETECTED', name='auditeventtype', native_enum=False), nullable=False),
    sa.Column('event_subtype', sa.String(length=60), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('tenant_slug', sa.String(length=80), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('signing_key_id', sa.String(length=60), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_actor'), 'audit_log_entries', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entry_hash'), 'audit_log_entries', ['entry_hash'], unique=True)
    op.create_index(op.f('ix_audit_log_entries_event_type'), 'audit_log_entries', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_occurred_at'), 'audit_log_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_sequence'), 'audit_log_entries', ['sequence'], unique=True)
    op.create_index(op.f('ix_audit_log_entries_severity'), 'audit_log_entries', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_tenant_id'), 'audit_log_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_tenant_slug'), 'audit_log_entries', ['tenant_slug'], unique=False)
    op.create_table('breach_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', name='breachseverity', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_tenant_id', sa.UUID(), nullable=True),
    sa.Column('target_tenant_id', sa.UUID(), nullable=True),
    sa.Column('resource', sa.String(length=160), nullable=True),
    sa.Column('principal', sa.String(length=160), nullable=True),
    sa.Column('action_taken', sa.String(length=160), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('VIOLATION', 'REVIEW', name='violationseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='violationstatus', native_enum=False), nullable=False),
    sa.Column('control_reference', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'REVERTED', name='configchangestatus', native_enum=False), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['config_parameters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('control_domain', sa.String(length=80), nullable=False),
    sa.Column('control_description', sa.String(length=160), nullable=False),
    sa.Column('control_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('MAPPED', 'PARTIAL', 'GAP', 'NOT_APPLICABLE', name='controlstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', 'control_domain', name='uq_control_domain_per_framework')
    )
    op.create_table('etcd_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_instance_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('raft_term', sa.Integer(), nullable=False),
    sa.Column('lag_ms', sa.Float(), nullable=False),
    sa.Column('db_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engine_instance_id'], ['engine_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_label', sa.String(length=80), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('hsm_object_id', sa.String(length=20), nullable=True),
    sa.Column('algorithm', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRING', 'RETIRED', 'PENDING', name='masterkeystatus', native_enum=False), nullable=False),
    sa.Column('rotation_policy_days', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('wraps_dek_count', sa.Integer(), nullable=False),
    sa.Column('throughput_ops', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['hsm_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['master_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_label')
    )
    op.create_index(op.f('ix_master_keys_status'), 'master_keys', ['status'], unique=False)
    op.create_table('system_metric_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_instance_id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.Enum('CPU_PERCENT', 'MEMORY_PERCENT', 'DISK_IO_MBPS', 'NETWORK_MBPS', 'GOROUTINES', 'GC_PAUSE_MS', 'OPEN_FDS', name='metrickey', native_enum=False), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engine_instance_id'], ['engine_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metric_samples_engine_instance_id'), 'system_metric_samples', ['engine_instance_id'], unique=False)
    op.create_index(op.f('ix_system_metric_samples_metric_key'), 'system_metric_samples', ['metric_key'], unique=False)
    op.create_index(op.f('ix_system_metric_samples_recorded_at'), 'system_metric_samples', ['recorded_at'], unique=False)
    op.create_table('tenant_backup_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CURRENT', 'STALE', 'PENDING', name='snapshotstatus', native_enum=False), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('retained_count', sa.Integer(), nullable=False),
    sa.Column('stale_reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_provisioning_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED', 'COMPLETE', 'ABORTED', name='provisioningjobstatus', native_enum=False), nullable=False),
    sa.Column('completed_steps', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.String(length=60), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_schema_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=160), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_anomaly_links',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_event_id'], ['anomaly_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'anomaly_event_id')
    )
    op.create_table('key_ceremonies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ceremony_ref', sa.String(length=40), nullable=False),
    sa.Column('master_key_id', sa.UUID(), nullable=False),
    sa.Column('predecessor_label', sa.String(length=80), nullable=True),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETE', 'ABORTED', name='ceremonystatus', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['master_key_id'], ['master_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ceremony_ref')
    )
    op.create_table('key_custodian_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ceremony_id', sa.UUID(), nullable=False),
    sa.Column('custodian_email', sa.String(length=120), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ceremony_id'], ['key_ceremonies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_custodian_approvals')
    op.drop_table('key_ceremonies')
    op.drop_table('incident_anomaly_links')
    op.drop_table('tenant_schema_validations')
    op.drop_table('tenant_provisioning_jobs')
    op.drop_table('tenant_backup_snapshots')
    op.drop_index(op.f('ix_system_metric_samples_recorded_at'), table_name='system_metric_samples')
    op.drop_index(op.f('ix_system_metric_samples_metric_key'), table_name='system_metric_samples')
    op.drop_index(op.f('ix_system_metric_samples_engine_instance_id'), table_name='system_metric_samples')
    op.drop_table('system_metric_samples')
    op.drop_index(op.f('ix_master_keys_status'), table_name='master_keys')
    op.drop_table('master_keys')
    op.drop_table('etcd_nodes')
    op.drop_table('control_mappings')
    op.drop_table('config_changes')
    op.drop_table('compliance_violations')
    op.drop_table('breach_alerts')
    op.drop_index(op.f('ix_audit_log_entries_tenant_slug'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_tenant_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_severity'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_sequence'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_occurred_at'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_event_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entry_hash'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_actor'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_api_endpoint_stats_recorded_at'), table_name='api_endpoint_stats')
    op.drop_index(op.f('ix_api_endpoint_stats_engine_instance_id'), table_name='api_endpoint_stats')
    op.drop_table('api_endpoint_stats')
    op.drop_index(op.f('ix_anomaly_events_tenant_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_status'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_severity'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_occurred_at'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_category'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('schema_validation_results')
    op.drop_table('incidents')
    op.drop_table('hsm_slots')
    op.drop_table('engine_instances')
    op.drop_table('crypto_algorithms')
    op.drop_index(op.f('ix_config_parameters_tier'), table_name='config_parameters')
    op.drop_index(op.f('ix_config_parameters_section'), table_name='config_parameters')
    op.drop_index(op.f('ix_config_parameters_key'), table_name='config_parameters')
    op.drop_table('config_parameters')
    op.drop_table('compliance_frameworks')
    op.drop_table('certificates')
    op.drop_table('behavioral_baselines')
    # ### end Alembic commands ###
