"""add oidc status fields to engine instance

Revision ID: 6ffb5af5dec7
Revises: d45ebfc59718
Create Date: 2026-07-03 08:46:27.052322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffb5af5dec7'
down_revision: Union[str, None] = 'd45ebfc59718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engine_instances', sa.Column('oidc_provider', sa.String(length=80), nullable=True))
    op.add_column('engine_instances', sa.Column('oidc_active_tokens', sa.Integer(), nullable=False))
    op.add_column('engine_instances', sa.Column('oidc_auth_rate', sa.Float(), nullable=False))
    op.add_column('engine_instances', sa.Column('oidc_failure_count', sa.Integer(), nullable=False))
    op.add_column('engine_instances', sa.Column('oidc_jwks_refreshed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('engine_instances', sa.Column('oidc_cert_valid_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engine_instances', 'oidc_cert_valid_until')
    op.drop_column('engine_instances', 'oidc_jwks_refreshed_at')
    op.drop_column('engine_instances', 'oidc_failure_count')
    op.drop_column('engine_instances', 'oidc_auth_rate')
    op.drop_column('engine_instances', 'oidc_active_tokens')
    op.drop_column('engine_instances', 'oidc_provider')
    # ### end Alembic commands ###
