"""add attestation runs

Revision ID: 6aef05f18fd0
Revises: 6ffb5af5dec7
Create Date: 2026-07-03 11:08:08.921124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aef05f18fd0'
down_revision: Union[str, None] = '6ffb5af5dec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attestation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('all_passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attestation_runs')
    # ### end Alembic commands ###
